### ISSUE TITLE
Add pyGi to images / virtualenv

### ISSUE THREAD

**Issue by CromefireHD** [rtfd/readthedocs-docker-images#31]
Because python-gi / python3-gi is not accessible from pypi it could not be accessed by the documentation, causing failure in build, when importing

**Comment by humitos** [comment]
@CromefireHD you could try the solution in the FAQ: http://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

... or maybe another thing it could work is taking a look at the conda environment option.

**Comment by CromefireHD** [comment]
So I did:
from unittest.mock import MagicMock


class Mock(MagicMock):
    @classmethod
    def __getattr__(cls, name):
        return MagicMock()

MOCK_MODULES = ["gi.repository"]
sys.modules.update((mod_name, Mock()) for mod_name in MOCK_MODULES)


And also:
MOCK_MODULES = ["gi.repository"]

And got:
/home/docs/checkouts/readthedocs.org/user_builds/pcu-api/checkouts/latest/docs/modules/gen_qr.rst:6:

 WARNING: autodoc: failed to import module 'pcu_api.gen_qr'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pcu-api/envs/latest/local/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pcu-api/envs/latest/local/lib/python3.5/site-packages/pcu_api-0.0.1a4-py3.5.egg/pcu_api/gen_qr.py", line 4, in <module>
    from pcu_api.qr_win import pil2win
  File "/home/docs/checkouts/readthedocs.org/user_builds/pcu-api/envs/latest/local/lib/python3.5/site-packages/pcu_api-0.0.1a4-py3.5.egg/pcu_api/qr_win.py", line 21, in <module>
    import gi
ImportError: No module named 'gi'

**Comment by CromefireHD** [comment]
Conda doesn't seems to be capable of that. I just can fix in in my local virtualenv with symlinks, but thats not possible at rtd

**Comment by CromefireHD** [comment]
Fixed it you'll need to mock `gi` and `gi.repository`
